#!/bin/bash

countreg() {
 count=0
 for i in $1/*; do
  if [ -f $i ]; then
   echo $i
   count=$(($count+1))
  fi
 done
 return $count
}

filesize() {
 total=0
 for i in $1/*; do
  if [ -f $i ]; then
   echo $i
   filesize=$(wc -c <$i)
   total=$(($total+$filesize))
  fi
 done
 return $total
}

biggestfile() {
 big=0
 for i in $1/*; do
  if [ -f $i ]; then
   fsize=$(wc -c <$i)
   if [ $fsize -ge $big ]; then
    big=$(($fsize))
   fi
  fi
 done
 return $big
}

countreg $1
echo "$? files in $1"
filesize $1
echo "$? total bytes in $1"
biggestfile $1
echo "the biggest file is $? bytes"
